export const styles = {
  container: { minHeight: '100vh', display: 'flex', flexDirection: 'column' },
  navbar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem 5%', borderBottom: '1px solid', position: 'sticky', top: 0, zIndex: 1000 },
  navBrand: { fontSize: '1.4rem', fontWeight: '900', color: '#3b82f6', cursor: 'pointer' },
  navLinks: { display: 'flex', gap: '20px', alignItems: 'center' },
  navItemBtn: { textDecoration: 'none', fontWeight: '600', padding: '5px 0' },
  themeToggleBtn: { border: 'none', background: 'none', fontSize: '1.2rem', cursor: 'pointer' },
  adminToggle: { padding: '8px 18px', background: '#3b82f6', color: '#fff', border: 'none', borderRadius: '12px', cursor: 'pointer', fontWeight: 'bold' },
  logoutBtn: { padding: '8px 18px', background: 'transparent', color: '#f43f5e', border: '2px solid #f43f5e', borderRadius: '12px', cursor: 'pointer', fontWeight: 'bold' },
  main: { flex: 1 },
  viewContainer: { maxWidth: '1200px', margin: '40px auto', padding: '0 20px', animation: 'fadeIn 0.5s' },
  sectionTitle: { fontSize: '2.5rem', fontWeight: '900', textAlign: 'center', marginBottom: '40px' },
  heroWrapper: { padding: '20px 4%' },
  hero: { height: '75vh', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', background: 'linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.6)), url("https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200")', backgroundSize: 'cover', backgroundPosition: 'center', color: '#fff', borderRadius: '50px', textAlign: 'center', boxShadow: '0 20px 40px rgba(0,0,0,0.2)' },
  heroContent: { padding: '0 20px' },
  heroTitle: { fontSize: '4.5rem', fontWeight: '900', marginBottom: '10px' },
  heroDivider: { width: '80px', height: '4px', background: '#3b82f6', margin: '20px auto', borderRadius: '10px' },
  heroSubtitle: { fontSize: '1.4rem', marginBottom: '40px', fontWeight: '300' },
  primaryBtn: { padding: '18px 50px', background: '#3b82f6', color: '#fff', textDecoration: 'none', borderRadius: '50px', fontWeight: 'bold' },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: '30px' },
  roomCard: { borderRadius: '30px', overflow: 'hidden', boxShadow: '0 15px 35px rgba(0,0,0,0.05)', textAlign: 'center', paddingBottom: '20px' },
  roomImg: { width: '100%', height: '220px', objectFit: 'cover' },
  roomName: { padding: '20px', fontSize: '1.4rem', fontWeight: '800' },
  roomDetails: { padding: '0 20px 20px' },
  priceText: { color: '#10b981', fontWeight: '900', fontSize: '1.2rem' },
  bookBtn: { width: '90%', padding: '15px', background: '#3b82f6', color: '#fff', border: 'none', borderRadius: '15px', fontWeight: 'bold', cursor:'pointer' },
  formCard: { padding: '40px', borderRadius: '35px', width: '400px', boxShadow: '0 10px 30px rgba(0,0,0,0.1)' },
  form: { display: 'flex', flexDirection: 'column', gap: '15px' },
  input: { padding: '16px', borderRadius: '15px', border: '1px solid', outline: 'none' },
  confirmBtn: { padding: '16px', background: '#10b981', color: '#fff', border: 'none', borderRadius: '15px', fontWeight: 'bold', cursor: 'pointer' },
  cancelBtn: { padding: '16px', background: '#64748b', color: '#fff', border: 'none', borderRadius: '15px', cursor: 'pointer' },
  tabBar: { display: 'flex', justifyContent: 'center', gap: '20px', marginBottom: '40px' },
  activeTab: { padding: '12px 30px', background: '#3b82f6', color: '#fff', border: 'none', borderRadius: '15px', fontWeight: 'bold' },
  inactiveTab: { padding: '12px 30px', border: '1px solid #e2e8f0', borderRadius: '15px', fontWeight: 'bold', cursor: 'pointer' },
  tableWrapper: { padding: '30px', borderRadius: '35px' },
  modernTable: { width: '100%', borderCollapse: 'collapse' },
  td: { padding: '20px 15px' },
  redDeleteBtn: { padding: '8px 18px', background: 'none', color: '#f43f5e', border: '2px solid #f43f5e', borderRadius: '12px', fontWeight: 'bold', cursor: 'pointer' },
  modalOverlay: { position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', background: 'rgba(0,0,0,0.7)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 2000 },
  footer: { color: '#94a3b8', padding: '30px', textAlign: 'center', marginTop: 'auto' },
  reviewFormSection: { padding: '40px', borderRadius: '30px', marginBottom: '40px' },
  formInline: { display: 'flex', flexDirection: 'column', gap: '20px' },
  postBtn: { padding: '15px', background: '#3b82f6', color: '#fff', border: 'none', borderRadius: '15px', fontWeight: 'bold', cursor:'pointer' },
  reviewsGridNew: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))', gap: '30px' },
  reviewCardNew: { padding: '35px', borderRadius: '25px' },
  contactGridNew: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '30px' },
  contactCardNew: { padding: '50px 30px', borderRadius: '40px', textAlign: 'center' }
};
